package com.jackson.blebridge.core.designsystem.theme.semantic.color

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import com.jackson.blebridge.core.designsystem.theme.primitive.color.ColorPalette

@Immutable
data class AppColors(
    val backgroundPrimary: Color,
    val backgroundSecondary: Color,
    val surfacePrimary: Color,
    val surfaceSecondary: Color,
    val surfaceVariant: Color,
    val inputBackground: Color,
    val surfaceInverse: Color,
    val borderNormal: Color,
    val borderSubtle: Color,
    val borderStrong: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textPlaceholder: Color,
    val textInverse: Color,
    val iconPrimary: Color,
    val iconSecondary: Color,
    val iconDisabled: Color,
    val server: Color,
    val onServer: Color,
    val serverContainer: Color,
    val onServerContainer: Color,
    val client: Color,
    val onClient: Color,
    val clientContainer: Color,
    val onClientContainer: Color,
    val success: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val error: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val warning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    val disabled: Color,
    val disabledContainer: Color,
    val onDisabledContainer: Color,
    val disabledBorder: Color,
    val advertising: Color,
    val advertisingContainer: Color,
    val onAdvertisingContainer: Color,
    val scrim: Color,
)

internal val LightAppColors = AppColors(
    backgroundPrimary = ColorPalette.white,
    backgroundSecondary = ColorPalette.gray75,
    surfacePrimary = ColorPalette.white,
    surfaceSecondary = ColorPalette.gray50,
    surfaceVariant = ColorPalette.gray150,
    inputBackground = ColorPalette.gray100,
    surfaceInverse = ColorPalette.gray900,
    borderNormal = ColorPalette.gray200,
    borderSubtle = ColorPalette.grayDivider,
    borderStrong = ColorPalette.gray300,
    textPrimary = ColorPalette.gray900,
    textSecondary = ColorPalette.gray700,
    textTertiary = ColorPalette.gray500,
    textPlaceholder = ColorPalette.grayPlaceholder,
    textInverse = ColorPalette.white,
    iconPrimary = ColorPalette.gray900,
    iconSecondary = ColorPalette.gray700,
    iconDisabled = ColorPalette.disabled,
    server = ColorPalette.server,
    onServer = ColorPalette.white,
    serverContainer = ColorPalette.serverContainer,
    onServerContainer = ColorPalette.serverStrong,
    client = ColorPalette.client,
    onClient = ColorPalette.black,
    clientContainer = ColorPalette.clientContainer,
    onClientContainer = ColorPalette.onClientContainer,
    success = ColorPalette.success,
    successContainer = ColorPalette.successContainer,
    onSuccessContainer = ColorPalette.onSuccessContainer,
    error = ColorPalette.error,
    errorContainer = ColorPalette.errorContainer,
    onErrorContainer = ColorPalette.onErrorContainer,
    warning = ColorPalette.warning,
    warningContainer = ColorPalette.warningContainer,
    onWarningContainer = ColorPalette.onWarningContainer,
    disabled = ColorPalette.disabled,
    disabledContainer = ColorPalette.gray150,
    onDisabledContainer = ColorPalette.disabledContent,
    disabledBorder = ColorPalette.gray300,
    advertising = ColorPalette.advertising,
    advertisingContainer = ColorPalette.advertisingContainer,
    onAdvertisingContainer = ColorPalette.onAdvertisingContainer,
    scrim = ColorPalette.scrim,
)

internal val DarkAppColors = AppColors(
    backgroundPrimary = ColorPalette.darkBackground,
    backgroundSecondary = ColorPalette.black,
    surfacePrimary = ColorPalette.darkSurface,
    surfaceSecondary = ColorPalette.darkBubble,
    surfaceVariant = ColorPalette.darkSurfaceVariant,
    inputBackground = ColorPalette.darkSurfaceVariant,
    surfaceInverse = ColorPalette.white,
    borderNormal = ColorPalette.darkOutline,
    borderSubtle = ColorPalette.darkSurfaceVariant,
    borderStrong = ColorPalette.gray600,
    textPrimary = ColorPalette.darkText,
    textSecondary = ColorPalette.darkTextSecondary,
    textTertiary = ColorPalette.gray550,
    textPlaceholder = ColorPalette.gray600,
    textInverse = ColorPalette.black,
    iconPrimary = ColorPalette.darkText,
    iconSecondary = ColorPalette.darkTextSecondary,
    iconDisabled = ColorPalette.gray600,
    server = ColorPalette.serverDark,
    onServer = ColorPalette.black,
    serverContainer = ColorPalette.serverContainerDark,
    onServerContainer = ColorPalette.onServerContainerDark,
    client = ColorPalette.clientDark,
    onClient = ColorPalette.black,
    clientContainer = ColorPalette.clientContainerDark,
    onClientContainer = ColorPalette.onClientContainerDark,
    success = ColorPalette.success,
    successContainer = ColorPalette.darkSurfaceVariant,
    onSuccessContainer = ColorPalette.success,
    error = ColorPalette.errorDark,
    errorContainer = ColorPalette.darkSurfaceVariant,
    onErrorContainer = ColorPalette.errorDark,
    warning = ColorPalette.warning,
    warningContainer = ColorPalette.darkSurfaceVariant,
    onWarningContainer = ColorPalette.warning,
    disabled = ColorPalette.gray600,
    disabledContainer = ColorPalette.darkSurfaceVariant,
    onDisabledContainer = ColorPalette.gray550,
    disabledBorder = ColorPalette.darkOutline,
    advertising = ColorPalette.advertisingDark,
    advertisingContainer = ColorPalette.advertisingContainerDark,
    onAdvertisingContainer = ColorPalette.onAdvertisingContainerDark,
    scrim = ColorPalette.scrim,
)

internal val LocalAppColors = staticCompositionLocalOf { LightAppColors }
